apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: obj-oct7-fb-1 
  janus-idp.io/tekton: obj-oct7-fb-1
  backstage.io/kubernetes-id: obj-oct7-fb-1
  backstage.io/kubernetes-namespace: obj-oct7-fb-1 
  app.kubernetes.io/part-of: obj-oct7-fb-1
resources: 
- application-dev.yaml